[phases.setup]
nixPkgs = ["python39", "ffmpeg"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["mkdir -p output"]

[start]
cmd = "gunicorn --chdir backend --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app"
